name: auto-format
on: pull_request
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 16
          
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
          
      - name: Install prettier
        run: |
          npm install -g prettier
          npm install -g prettier prettier-plugin-java
          
      - name: Run formatter
        run: |
          prettier --tab-width 4 . --write
          
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
        
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -m "[skip ci] auto format"
          git push
